DO $$ BEGIN
    CREATE TYPE base_unit AS enum ('WHOLE_CURRENCY', 'WHOLE_CENT', 'HUNDREDTH_CENT', 'THOUSANDTH_CENT', 'TEN_THOUSANDTH_CENT', 'MILLIONTH_CENT');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;
