# Well this is pretty annoying

service: user-existence-api # NOTE: update this with your service name

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost
    stages:
      - local
    debug: true
  stage:
    - local
  mountCode: True
  thisStage: ${opt:stage, self:provider.stage}
  thisProcess:
    NODE_ENV:
      prod: "production"
      dev: "development"
      local: "lamblocal"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: local
  deploymentBucket:
    pluto.user.existence.lambdas

functions:
  create:
    handler: account.create
    name: create-account
    events:
      - http:
          path: create
          method: post
    environment:
      NODE_ENV: ${self:custom.thisProcess.NODE_ENV.${self:custom.thisStage}}
      DEBUG: pluto:*

package:
  include:
    - node_modules/rds-common/**