# Unnamed serverless API

service: auth-api # NOTE: update this with your service name

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost
    stages:
      - dev
      - local
    debug: true
  stages:
    - local
    - dev
  thisStage: ${opt:stage, self:provider.stage}
  thisProcess:
    NODE_ENV:
      prod: "production"
      dev: "development"
      local: "lamblocal"

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev

functions:
  insertUserCredentials:
    handler: user-insertion-handler.insertUserCredentials
    events:
      - http:
          path: create-new-user
          method: post
    environment:
      NODE_ENV: ${self:custom.thisProcess.NODE_ENV.${self:custom.thisStage}}
      DEBUG: pluto:*
  verifyUserCredentials:
    handler: user-credentials-verification-handler.verifyUserCredentials
    events:
      - http:
          path: verify-user-credentials
          method: post
    environment:
      NODE_ENV: ${self:custom.thisProcess.NODE_ENV.${self:custom.thisStage}}
      DEBUG: pluto:*
  verifyJsonWebToken:
    handler: jwt-handler.verifyJsonWebToken
    events:
      - http:
          path: verify-jwt
          method: post
    environment:
      NODE_ENV: ${self:custom.thisProcess.NODE_ENV.${self:custom.thisStage}}
      DEBUG: pluto:*
  signJsonWebToken:
    handler: jwt-handler.signJsonWebToken
    events:
      - http:
          path: sign-jwt
          method: get
    environment:
      NODE_ENV: ${self:custom.thisProcess.NODE_ENV.${self:custom.thisStage}}
      DEBUG: pluto:*
