# Welcome to Serverless!

service: user-activity-api

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost
    stages:
      - dev
      - local
    debug: true
  stages:
    - local
    - dev
  thisStage: ${opt:stage, self:provider.stage}
  thisProcess:
    NODE_ENV:
      prod: "production"
      dev: "development"
      local: "lamblocal"

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  stage: dev
  deploymentBucket:
    pluto.user.action.lambdas

functions:
  save:
    handler: savetxhandler.save
    name: add-savings
    events:
      - http:
          path: save
          method: post
    environment:
      NODE_ENV: ${self:custom.thisProcess.NODE_ENV.${self:custom.thisStage}}
      DEBUG: pluto:*

package:
  include:
    - node_modules/rds-common/**