AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the table will hold the password policy enforced during signup'
Resources:
 PasswordPolicyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "PasswordPolicyTable"
      AttributeDefinitions:
      -
        AttributeName: "AuthPasswordPolicy"
        AttributeType: "S"
      -
        AttributeName: "LastUpdatedTimestamp"
        AttributeType: "N"
      KeySchema:
      - AttributeName: "AuthPasswordPolicy"
        KeyType: HASH
      - AttributeName: "LastUpdatedTimestamp"
        KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
