AWSTemplateFormatVersion: '2010-09-09'
Description: 'Creates the table that hold critical system-wide but rarely used variables, e.g., float shares, clients'
Resources:
  systemVariableTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "SystemVariableTable"
      AttributeDefinitions:
      -
        AttributeName: "VariableKey"
        AttributeType: "S"
      -
        AttributeName: "LastUpdatedTimestamp"
        AttributeType: "N"
      KeySchema:
      - AttributeName: "VariableKey"
        KeyType: HASH
      - AttributeName: "LastUpdatedTimestamp"
        KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
  responsibleClientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ResponsibleClientsTable"
      AttributeDefinitions:
      -
        AttributeName: "ResponsibleClientId"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "ResponsibleClientId"
        KeyType: PRIMARY
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
